import Head from 'next/head'
import DisplayChess from '../components/DisplayChess';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DisplayChess />
    </div>
  )
}